<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_element_info_alter().
 */
function lock_sitefarm_features_element_info_alter(array &$info) {
  if (isset($info['operations'])) {
    $info['operations']['#attached']['library'][] = 'lock_sitefarm_features/lock_sitefarm_features.styles';
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function lock_sitefarm_features_entity_operation_alter(array &$operations, EntityInterface $entity) {
  /** @var \Drupal\lock_sitefarm_features\Access\LockFeatureAccess $lock */
  $lock = \Drupal::service('access_check.lock_sitefarm_features');
  $entity_type = $entity->getEntityTypeId();

  if (\Drupal::currentUser()->id() != 1) {
    $locked_entities = array_merge(
      $lock->getLockedNodeTypes(),
      $lock->getLockedBlockTypes(),
      $lock->getLockedTextFormats(),
      $lock->getLockedPathautoPatterns()
    );

    // Lock down Image styles except for the Flush operation
    $theme = \Drupal::service('theme_handler')->getDefault();
    /** @var \Drupal\Core\Config\ConfigFactoryInterface $config */
    $config = \Drupal::config('lock_sitefarm_features.settings');
    $locked_themes = $config->get('locked_themes');
    if ($entity_type == 'image_style'
      && in_array($theme, $locked_themes)
      && ($lock->matchesLockedPattern($entity->id()) || in_array($entity->id(), $lock->getLockedImageStyles()))
    ) {
      foreach ($operations as $key => $value) {
        if ($key != 'flush') {
          unset($operations[$key]);
        }
      }
    }

    // Partially lock Taxonomy, but still leave listing and adding terms
    elseif ($entity_type == 'taxonomy_vocabulary'
      && ($lock->matchesLockedPattern($entity->id()) || in_array($entity->id(), $lock->getLockedTaxonomy()))
    ) {
      foreach ($operations as $key => $value) {
        if ($key != 'list' && $key != 'add') {
          unset($operations[$key]);
        }
      }
    }

    // Partially lock Views, but still leave duplicating and disabling
    elseif ($entity_type == 'view'
      && ($lock->matchesLockedPattern($entity->id()) || in_array($entity->id(), $lock->getLockedViews()))
    ) {
      unset($operations['edit']);
      unset($operations['delete']);
    }

    // Completely lock entity operations
    elseif ($lock->matchesLockedPattern($entity->id()) || in_array($entity->id(), $locked_entities)) {
      $operations = [
        'locked' => [
          'title' => t('Locked')
        ]
      ];
    }
  }

}
