<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * For the ID form_block.
 */
function sitefarm_marketing_highlight_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Get the Sitefarm forms helper service
  $form_helper = \Drupal::service('sf.block_form_helpers');
  $bundle = $form_helper->getBlockContentBundle($form_state);

  if ($bundle == 'sf_marketing_highlight' || $bundle == 'sf_marketing_highlight_horizntl') {
    $form_helper->hideBlockTitleCheckbox($form);
  }
}
