<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function sitefarm_focal_link_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'block_content_sf_focal_link_form'
    || $form_id == 'block_content_sf_focal_link_edit_form') {
    // Set conditional state on Image
    $form['field_sf_image']['#states'] = array(
      'visible' => array(
        ':input[name="field_sf_icon_choice[value]"]' => array('checked' => FALSE),
      ),
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * For the ID form_block.
 */
function sitefarm_focal_link_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Get the Sitefarm forms helper service
  $form_helper = \Drupal::service('sf.block_form_helpers');

  if ($form_helper->getBlockContentBundle($form_state) == 'sf_focal_link') {
    $form_helper->hideBlockTitleCheckbox($form);
  }
}
