<?php

/**
 * @file
 */

/**
 * Removes Focal Link icon field
 */
function sitefarm_focal_link_update_8101(&$sandbox) {
  $messages = array();

  // Fetch the field config storage
  $field_config = \Drupal::entityTypeManager()->getStorage('field_config');

  // Brand Textbox field
  $field = $field_config->load('block_content.sf_focal_link.field_sf_icon');
  $field->delete();
  $messages[] = t('The Focal Link "Icon" field has been deleted!');

  return implode("\n", $messages);
}
