<?php

/**
 * @file
 */

/**
 * Reset the Basic Page Simple XML Sitemap config to default
 */
function sitefarm_page_update_8101(&$sandbox) {
  /** @var \Drupal\config_update\ConfigRevertInterface $config_revert */
  $config_revert = \Drupal::service('config_update.config_update');
  $config_revert->revert('system.simple', 'simple_sitemap.bundle_settings.node.sf_page');

  return t('Simple XML Sitemap page config updated.');
}
